name: First Workflow

on:
  push: 
    branches:
      - main
      # - Staging
      # - development
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "This is my first GitHub Actions workflow!"
