name: Frontend CI

on:
  pull_request:
    branches:
      - main
      - development

  push:
    branches:
      - main
      # - Staging
      - development
jobs:
  quality-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format:check

      - name: Run TypeScript check
        run: npm run type-check

      - name: Run Knip check
        run: npx knip

      - name: Run build project
        run: npm run build
